### ISSUE TITLE
Improvements for preparation section 

### ISSUE THREAD

**Issue by zelima** [otruja/bitcoin-prices#2]
As a newbie user, I want instructions for preparing data to be as dumb as possible, so that I do not have to do additional research what `pandas` is and how to run python scripts. 

Eg:

### install:

* you will need python 3.x to be installed on your machine
* install pandas with pip

```
pip install pandas 
```

### run the sctript

```
python scripts/process.py
```

**Comment by otruja** [comment]
Okay. Could you please review if everything is fine now?

**Comment by zelima** [comment]
@otruja Ideally you would refer to the issue in your commit message when committing. That way I can easily review related changes.

Current commit messages are not really helpful: `Signed-off-by: Vladimir S <otruja@mail.ru>`. 

Anyway, I think this is fixed now. Please close it

**Comment by otruja** [comment]
FIXED
